### ISSUE TITLE
dont edit my issue you clown

### ISSUE THREAD

**Issue by AzSumPesho** [xKiian/go6-leak#3]
faggot stop editing my issue <3

**Comment by AzSumPesho** [comment]
closing the issue as you wont stop editing it

**Comment by imvast** [comment]
folded

**Comment by AzSumPesho** [comment]
> 

i leaked his face but he edited the issue to remove it

**Comment by xKiian** [comment]
totally my face 💀

**Comment by very-good-name** [comment]
best face https://cdn.discordapp.com/attachments/1116476571742654574/1117034447389343764/image.png
